# Generated by Django 4.0.3 on 2024-03-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviesCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movie_app_backend/templates/movies/images')),
                ('genre', models.CharField(choices=[('ACT', 'ACTION'), ('DRA', 'DRAMA'), ('COM', 'COMEDY'), ('ROM', 'ROMANCE')], max_length=3)),
                ('releaseDate', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('userRating', models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST_WATCHED'), ('TR', 'TOP_RATED')], max_length=2)),
                ('viewsCount', models.IntegerField(default=0)),
                ('trailerLink', models.CharField(blank=True, default='', max_length=100)),
                ('movieSummary', models.TextField(default='', max_length=10000)),
                ('movieSynopsys', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
