# Generated by Django 4.0.3 on 2024-03-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madb_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescatalog',
            name='image',
            field=models.ImageField(upload_to='madb_catalog/templates/movies_catalog/images'),
        ),
    ]
