# Generated by Django 4.0.3 on 2024-03-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madb_backend', '0005_alter_moviescatalog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescatalog',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moviescatalog',
            name='trailerLink',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
