# Generated by Django 4.0.3 on 2024-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madb_backend', '0006_alter_moviescatalog_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescatalog',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='moviescatalog',
            name='director',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moviescatalog',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/movies/'),
        ),
        migrations.AlterField(
            model_name='moviescatalog',
            name='movieSummary',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='moviescatalog',
            name='movieSynopsys',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='moviescatalog',
            name='userRating',
            field=models.CharField(blank=True, choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST_WATCHED'), ('TR', 'TOP_RATED')], max_length=2),
        ),
        migrations.AlterField(
            model_name='moviescatalog',
            name='viewsCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
