# Generated by Django 4.0.3 on 2024-03-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madb_backend', '0007_alter_moviescatalog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescatalog',
            name='image',
            field=models.ImageField(blank=True, default='images/movies/default.webp', upload_to='images/movies/'),
        ),
    ]
