# Generated by Django 5.0.3 on 2024-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madb_backend', '0011_alter_moviescatalog_moviesynopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescatalog',
            name='movieSynopsis',
            field=models.TextField(blank=True, default='', max_length=20000),
        ),
    ]
