# Generated by Django 5.0.3 on 2024-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madb_backend', '0013_alter_moviescatalog_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescatalog',
            name='userRating',
            field=models.CharField(blank=True, choices=[('Recently Added', 'RECENTLY ADDED'), ('Most watched', 'MOST_WATCHED'), ('Top rated', 'TOP_RATED')], max_length=14),
        ),
    ]
